small:
  d_model: 768
  d_ff: 3072
  num_layers: 12
  num_heads: 12
medium:
  d_model: 1024
  d_ff: 4096
  num_layers: 24
  num_heads: 16
large:
  d_model: 1280
  d_ff: 5129
  num_layers: 36
  num_heads: 20
xl:
  d_model: 1600
  d_ff: 6400
  num_layers: 48
  num_heads: 25
2.7B:
  d_model: 2560
  d_ff: 10240
  num_layers: 32
  num_heads: 32

vocab_size: 10000
batch_size: 2
rope_theta: 100000